"""Stage 7b: Monogenic disease panel report.

Reshapes the actionable variants already in DuckDB against a curated disease → gene
panel, and interprets each person's genotype *in light of inheritance mode*:

  - AD (dominant):  one pathogenic allele ⇒ at risk.
  - AR (recessive): homozygous ⇒ affected; two different het alleles in one gene ⇒
                    possible compound het (affected); a single het ⇒ carrier.
  - XL (X-linked):  males hemizygous ⇒ affected; females het ⇒ carrier, hom ⇒ affected.

Output per sample groups conditions into "disease risk" (affected/at-risk) vs
"carrier status", plus a family-level reproductive-risk check: recessive genes where
two members both carry a pathogenic allele. Build-agnostic — it queries `gene` and
`clinvar_sig`, so it runs unchanged on GRCh37 (legacy) or GRCh38 data.
"""

from __future__ import annotations

from pathlib import Path

from . import reportpaths
from . import clinsig, config, penetrance
from .load import TABLE, connect
from .snapshot import load_manifest
from .util import (disease_name as _disease, find_row, log, read_tsv,
                   review_stars as _stars, write_report)


def sql_in_list(values) -> str:
    """Render a Python string collection as the body of a SQL `IN (...)` clause — escapes
    embedded quotes and renders `NULL` for an empty collection (`col IN (NULL)` is valid SQL
    that matches nothing, unlike the syntax-error `col IN ()`). `panel` is a leaf among the
    acmg/panel/phasing/provenance quartet (imports none of the other three), so it hosts this
    shared helper without creating an import cycle — acmg and phasing already import from
    here, and provenance imports acmg."""
    vals = sorted({str(v) for v in values})
    if not vals:
        return "NULL"
    return ", ".join("'" + v.replace("'", "''") + "'" for v in vals)


_CAVEAT = ("_Generated by Genome Ledger. Research-grade, not a clinical diagnosis — "
           "confirm any finding with a clinical geneticist. Carrier/affected status is "
           "inferred from ClinVar-pathogenic variants under the listed inheritance mode._")

# S2: applies to every affected/at-risk row that has no gene-specific penetrance.note
# (see _row_md) — omission must never read as "this one is certain."
_GENERIC_PENETRANCE_CAVEAT = (
    "_A pathogenic genotype means elevated risk, not certainty. Most monogenic "
    "conditions have incomplete penetrance and/or variable expressivity (age of onset, "
    "severity) even when not individually quantified above — and for the minority of "
    "conditions that genuinely are highly/fully penetrant, that is not a reason to "
    "discount the finding either._")


# --- panel + variant model ---------------------------------------------------
class _Disease:
    __slots__ = ("name", "genes", "inh", "note")

    def __init__(self, name: str, genes: list[str], inh: str, note: str):
        self.name, self.genes, self.inh, self.note = name, genes, inh, note


def load_panel() -> list[_Disease]:
    rows = read_tsv(config.PANEL_FILE)
    if not rows:
        raise SystemExit(f"Panel file empty or missing: {config.PANEL_FILE}")
    return [_Disease(r["disease"], [g.strip() for g in r["genes"].split(",")],
                     r["inheritance"].strip().upper(), (r.get("note") or "").strip())
            for r in rows]


def _sex_of(sample: str) -> str:
    # Same lookup as ancestry._sex: samples present only in the incoming manifest must
    # still resolve — a male missed here would read an X-linked variant as "carrier"
    # instead of "affected".
    row = find_row(config.SAMPLES_TSV, sample_id=sample) or \
        find_row(config.INCOMING_MANIFEST, sample=sample) or {}
    return row.get("sex", "").lower()


def _is_male(sex: str) -> bool:
    return sex in ("male", "m", "1")


def _actionable_by_gene(con, snapshot_id: str, sample: str) -> dict[str, list[dict]]:
    """All actionable variants for a sample, indexed by gene symbol."""
    rows = con.execute(f"""
        SELECT gene, chrom, pos, ref, alt, clinvar_sig, clinvar_revstat,
               clinvar_disease, zygosity
        FROM {TABLE}
        WHERE snapshot_id = ? AND sample_id = ? AND gene IS NOT NULL
          AND {clinsig.sql_actionable()}
    """, [snapshot_id, sample]).fetchall()
    by_gene: dict[str, list[dict]] = {}
    for gene, chrom, pos, ref, alt, sig, rev, dis, zyg in rows:
        by_gene.setdefault(gene, []).append({
            "gene": gene, "key": (chrom, pos, ref, alt), "sig": sig, "rev": rev,
            "disease": dis, "zyg": (zyg or "").upper(),
            "label": f"{chrom}:{pos} {ref}>{alt}",
        })
    return by_gene


# --- inheritance-aware status ------------------------------------------------
# status code → (rank for sorting, is a "carrier-only" finding)
_AFFECTED, _ATRISK, _COMPOUND, _CARRIER = "affected", "at-risk", "compound", "carrier"
_RANK = {_AFFECTED: 0, _COMPOUND: 1, _ATRISK: 2, _CARRIER: 3}
_LABEL = {
    _AFFECTED: "Affected",
    _ATRISK: "At risk (dominant)",
    _COMPOUND: "Possible compound het — review",
    _CARRIER: "Carrier (1 allele)",
}


def _status(inh: str, sex: str, variants: list[dict]) -> str | None:
    zygs = [v["zyg"] for v in variants]
    has_hom = "HOM" in zygs
    n_het = zygs.count("HET")
    # compound het only counts when two *different* alleles hit the same gene.
    by_gene_hets: dict[str, set] = {}
    for v in variants:
        if v["zyg"] == "HET":
            by_gene_hets.setdefault(v["gene"], set()).add(v["key"])
    compound = any(len(keys) >= 2 for keys in by_gene_hets.values())

    if inh == "AD":
        return _ATRISK if (has_hom or n_het) else None
    if inh == "AR":
        if has_hom:
            return _AFFECTED
        if compound:
            return _COMPOUND
        return _CARRIER if n_het else None
    if inh == "XL":
        if _is_male(sex):
            return _AFFECTED if (has_hom or n_het) else None
        if has_hom:
            return _AFFECTED
        # Two different pathogenic hets in one X-linked gene is a compound heterozygote, the
        # same both-copies-hit situation the AR branch already treats as affected — the check
        # was simply AR-only, so an XL female with two hits was reported as a plain "Carrier".
        # (X-inactivation makes expression less predictable than in an autosomal recessive,
        # which is a reason to flag for review, not a reason to call it carrier status.)
        if compound:
            return _COMPOUND
        return _CARRIER if n_het else None
    # Unknown inheritance: report presence without a confident call.
    return _ATRISK if (has_hom or n_het) else None


# --- rendering ---------------------------------------------------------------
_HEADER = "| Disease | Status | Gene | Variant(s) | ClinVar | Review |"
_SEP = "|---------|--------|------|------------|---------|:------:|"
# Disease-risk table adds a Penetrance column; carrier table doesn't (carrier status
# itself is the caveat — a carrier is not the one at elevated disease risk here).
_HEADER_PRIMARY = "| Disease | Status | Gene | Variant(s) | ClinVar | Review | Penetrance |"
_SEP_PRIMARY = "|---------|--------|------|------------|---------|:------:|------------|"


def _row_md(dz: _Disease, status: str, variants: list[dict], primary: bool = False) -> str:
    best = max(_stars(v["rev"]) for v in variants)
    vis = "; ".join(sorted(f"{v['gene']} {v['label']} ({v['zyg'].title()})"
                           for v in variants))
    # One cell per distinct classification, joined with a comma: `/` already means
    # something inside a ClinVar value, and `|` would split the table row.
    sigs = ", ".join(sorted({clinsig.cell(v["sig"]) for v in variants}))
    note = f" ⚠️ {dz.note}" if dz.note else ""
    row = (f"| {dz.name}{note} | **{_LABEL[status]}** | "
           f"{','.join(sorted({v['gene'] for v in variants}))} | {vis} | "
           f"{sigs} | {'★' * best or '0★'} |")
    if primary:
        pen = penetrance.note_for(sorted({v["gene"] for v in variants}))
        row += f" {pen} |" if pen else " _(see general caveat below)_ |"
    return row


def panel_report(snapshot_id: str) -> list[Path]:
    panel = load_panel()
    con = connect()
    meta = load_manifest(snapshot_id)
    written = []

    samples = [r[0] for r in con.execute(
        f"SELECT DISTINCT sample_id FROM {TABLE} WHERE snapshot_id = ? ORDER BY 1",
        [snapshot_id]).fetchall()]

    n_genes = len({g for d in panel for g in d.genes})
    # ar_carriers[gene][sample] = that sample's AR status in gene — drives the family
    # reproductive-risk check. Every non-None AR status carries a pathogenic allele
    # (carrier: 1 allele; affected/compound: 2), so all three feed the index — a
    # hom/compound member paired with a carrier is a *higher* risk than carrier×carrier
    # and must not be dropped.
    ar_carriers: dict[str, dict[str, str]] = {}

    for sample in samples:
        sex = _sex_of(sample)
        by_gene = _actionable_by_gene(con, snapshot_id, sample)
        primary, carriers = [], []
        for dz in panel:
            hits = [v for g in dz.genes for v in by_gene.get(g, [])]
            if not hits:
                continue
            status, per_gene = disease_status(dz, sex, by_gene)
            if status is None:
                continue
            (carriers if status == _CARRIER else primary).append((dz, status, hits))
            if dz.inh == "AR":
                for g, gene_status in per_gene.items():
                    index_ar_status(ar_carriers, g, sample, gene_status)

        primary.sort(key=lambda t: (_RANK[t[1]], t[0].name))
        carriers.sort(key=lambda t: t[0].name)

        lines = [
            f"# Monogenic panel — {sample}",
            "",
            f"- **Snapshot:** `{snapshot_id}`  (ClinVar {meta['clinvar_date']}, "
            f"build {meta.get('build', config.BUILD)})",
            f"- **Panel:** {len(panel)} diseases / {n_genes} genes "
            f"(`{config.PANEL_FILE.name}`)",
            f"- **Findings:** {len(primary)} disease-risk, {len(carriers)} carrier",
            "",
            "## Disease risk (affected / at-risk)",
            "",
            _HEADER_PRIMARY, _SEP_PRIMARY,
        ]
        lines += [_row_md(*t, primary=True) for t in primary] or ["| _none_ | | | | | | |"]
        # S2: only show the generic caveat when some primary finding actually relied on
        # it — an all-curated report shouldn't carry redundant boilerplate.
        notes = [penetrance.note_for(sorted({v["gene"] for v in hits}))
                 for _, _, hits in primary]
        if any(n is None for n in notes):
            lines += ["", _GENERIC_PENETRANCE_CAVEAT]
        # Same rule one step further: a quoted lifetime-risk range has to say where it came
        # from, and the explanation appears only when a row actually quotes one.
        if any(penetrance.is_ascertained(n) for n in notes):
            lines += ["", penetrance.ASCERTAINMENT_NOTE]
        lines += [
            "",
            "## Carrier status (recessive / X-linked, single allele)",
            "_A carrier is typically healthy; relevant for reproductive risk "
            "(see family report when both partners carry the same gene)._",
            "",
            _HEADER, _SEP,
        ]
        lines += [_row_md(*t) for t in carriers] or ["| _none_ | | | | | |"]
        lines += ["", "## Caveats", _CAVEAT, ""]

        path = reportpaths.snapshot_report("panel", sample, snapshot_id)
        write_report(path, lines)
        written.append(path)
        log.info("Panel report: %s (%d disease-risk, %d carrier)",
                 path, len(primary), len(carriers))

    fam = _family_report(snapshot_id, meta, panel, ar_carriers)
    if fam:
        written.append(fam)
    con.close()
    return written


# Per-child probability that a given AR status passes a pathogenic allele, as (low, high).
# A carrier (1 allele) passes it half the time; an affected homozygote (both copies hit)
# always has one to give. _COMPOUND is neither: it is two *different* damaging alleles in
# one gene with the phase UNRESOLVED, which is why the panel labels it "Possible compound
# het — review". In-trans it is a genuine both-copies-hit and passes an allele every time;
# in-cis both alleles sit on one copy and the person is functionally a carrier. Scoring it
# as a flat 1.0 turned an open question into a definitive 50%/100% figure on a family
# reproductive-risk table. Report the range and say what would close it.
_PASS_PROB = {_CARRIER: (0.5, 0.5), _AFFECTED: (1.0, 1.0), _COMPOUND: (0.5, 1.0)}
_SHORT_LABEL = {_AFFECTED: "affected", _COMPOUND: "possible compound het",
                _CARRIER: "carrier"}


def disease_status(dz: _Disease, sex: str, by_gene: dict[str, list[dict]]):
    """(row status, {gene: that gene's status}) for one panel disease.

    Status is computed PER GENE, not over the disease's pooled hits. `_status` reads
    has_hom/n_het across everything it is given, so for a multi-gene disease a homozygote in
    one gene made a plain heterozygote in another read as affected — and that inflated status
    was then written into the AR carrier index for *both* genes, doubling the second gene's
    transmission probability in the family reproductive-risk table. Recessive inheritance is
    a property of one gene's two copies; it does not pool across genes. (`_status`'s own
    compound-het check was already per-gene; has_hom and n_het were not.)

    The row status is the most severe of the per-gene ones, which is what the pooled call
    produced anyway — only the per-gene index was wrong.
    """
    per_gene: dict[str, str] = {}
    for gene in dz.genes:
        hits = by_gene.get(gene)
        if not hits:
            continue
        st = _status(dz.inh, sex, hits)
        if st is not None:
            per_gene[gene] = st
    if not per_gene:
        return None, {}
    return min(per_gene.values(), key=lambda s: _RANK[s]), per_gene


def index_ar_status(index: dict[str, dict[str, str]], gene: str, sample: str,
                    status: str) -> None:
    """Record `sample`'s AR status in `gene`, keeping the MOST SEVERE of any statuses
    already recorded. One gene can sit in two AR panel diseases, so a sample can be
    affected for one and a carrier for the other; plain assignment is last-wins, and a
    later 'carrier' overwriting an earlier 'affected' would *understate* the child risk
    in the family report — the exact failure the index was widened to fix."""
    prior = index.setdefault(gene, {}).get(sample)
    if prior is None or _RANK[status] < _RANK[prior]:
        index[gene][sample] = status


def _pairing_risk_text(statuses: dict[str, str]) -> str:
    """Per-child affected-risk for *whichever two* of the listed members turn out to be
    reproductive partners — members here are not necessarily partners with each other, so
    this reports every distinct pairwise risk rather than asserting one number. With the
    usual two members and both statuses resolved it collapses to a single percentage;
    carrier×carrier is the 25% case the report was originally built around,
    affected×carrier is 50%, affected×affected is 100%.

    Two independent things widen it into a range, and the text names whichever applies:
    more than one candidate pairing, and an unresolved "possible compound het" whose
    per-child transmission is only bounded (0.5–1.0) until the phase is known.
    """
    names = sorted(statuses)
    pairs = [(a, b) for i, a in enumerate(names) for b in names[i + 1:]]
    lo = min(_PASS_PROB[statuses[a]][0] * _PASS_PROB[statuses[b]][0] for a, b in pairs)
    hi = max(_PASS_PROB[statuses[a]][1] * _PASS_PROB[statuses[b]][1] for a, b in pairs)
    lo, hi = round(lo * 100), round(hi * 100)
    if lo == hi:
        return f"{lo}%"
    why = []
    if len(pairs) > 1:
        why.append("depends on which two are partners")
    if any(_PASS_PROB[st][0] != _PASS_PROB[st][1] for st in statuses.values()):
        why.append("compound-het phase unresolved — run `phase`")
    return f"{lo}–{hi}% ({'; '.join(why)})"


def family_risk_rows(panel: list[_Disease],
                      ar_carriers: dict[str, dict[str, str]]) -> list[tuple[str, str, str, str]]:
    """Pure assembly of family-report rows from the gene→{sample: AR status} carrier index —
    factored out of `_family_report` so it's unit-testable without DuckDB. Returns
    (disease, gene, members_text, risk_text), one row per AR gene shared by ≥2 members."""
    gene_to_disease = {g: d.name for d in panel if d.inh == "AR" for g in d.genes}
    rows = []
    for gene in sorted(ar_carriers):
        statuses = ar_carriers[gene]
        if len(statuses) < 2:
            continue
        members = ", ".join(f"{s} ({_SHORT_LABEL[status]})"
                            for s, status in sorted(statuses.items()))
        rows.append((gene_to_disease.get(gene, "?"), gene, members,
                     _pairing_risk_text(statuses)))
    return rows


def _family_report(snapshot_id, meta, panel, ar_carriers) -> Path | None:
    """Recessive genes where ≥2 members carry a pathogenic allele (carrier, affected, or
    compound het all count — see item 5) → reproductive risk for a child of that pairing."""
    rows = family_risk_rows(panel, ar_carriers)
    path = reportpaths.family_report("panel_family", snapshot_id)
    if not rows:
        # A previous run's report must not survive its findings. Returning early left
        # panel_family.md on disk asserting a shared carrier risk that this snapshot no
        # longer finds — still discoverable by render and by anything reading the reports tree.
        for stale in (path, path.with_suffix(".html")):
            if stale.exists():
                stale.unlink()
                log.info("No shared recessive gene this snapshot — removed the stale %s.",
                         stale.name)
        return None
    lines = [
        "# Monogenic panel — family reproductive risk",
        "",
        f"- **Snapshot:** `{snapshot_id}`  (ClinVar {meta['clinvar_date']})",
        "",
        "Recessive genes in which more than one family member carries a ClinVar-pathogenic "
        "allele — carrier (1 allele), affected (homozygous), or possible compound het (2 "
        "different damaging alleles) all count, since all three can pass a pathogenic allele "
        "to a child. If two of the members below are reproductive partners, each child's "
        "affected risk depends on both members' genotypes — confirm with phased/clinical "
        "testing.",
        "",
        "A **possible compound het** is two different damaging alleles in one gene whose "
        "phase is not yet known. In-trans both copies are hit and the member always passes "
        "a pathogenic allele; in-cis the alleles share one copy and the member transmits "
        "like a carrier. Its risk is therefore given as a range until `phase` resolves it, "
        "rather than assumed to be the worse case.",
        "",
        "| Disease | Gene | Members (status) | Child risk if partners |",
        "|---------|------|-------------------|-------------------------|",
    ]
    for disease, gene, members, risk in rows:
        lines.append(f"| {disease} | {gene} | {members} | {risk} |")
    lines += ["", "## Caveats", _CAVEAT, ""]
    write_report(path, lines)
    log.info("Panel family report: %s (%d shared recessive gene(s))", path, len(rows))
    return path
