"""Stage 7: FULL report — current actionable variants per family member."""

from __future__ import annotations

from pathlib import Path

from . import reportpaths
from . import allele_balance, alphamissense, clinsig, config, limitations, spliceai
from .load import TABLE, connect
from .snapshot import load_manifest
from .util import disease_name as _disease, log, review_stars as _stars, write_report


def _samples_for(snapshot_id: str, con) -> list[str]:
    return [r[0] for r in con.execute(
        f"SELECT DISTINCT sample_id FROM {TABLE} WHERE snapshot_id = ? ORDER BY 1",
        [snapshot_id]).fetchall()]


def _rarity(af) -> str:
    if af is None:
        return "novel/absent"
    if af < config.RARE_AF_THRESHOLD:
        return f"rare ({af:.2g})"
    return f"common ({af:.2g})"


_HEADER = "| Gene | Disease | Variant | ClinVar | Review | gnomAD | Zyg |"
_SEP = "|------|---------|---------|---------|:------:|--------|-----|"
_CAVEAT = ("_Generated by Genome Ledger. Not a clinical diagnosis — confirm any "
           "finding with a clinical geneticist._")


def _render(r, ab=None) -> str:
    """One table row. `ab` is the {key: (alt_reads, total)} allele-balance map for the
    sample; a het call below config.LOW_VAF_THRESHOLD gets a review flag in the Zyg cell."""
    gene, dis, chrom, pos, ref, alt, sig, rev, af, zyg = r
    stars = _stars(rev)
    zcell = allele_balance.label(zyg, (ab or {}).get((chrom, pos, ref, alt)))
    return (f"| {gene or '?'} | {_disease(dis)} | {chrom}:{pos} {ref}>{alt} | "
            f"{clinsig.cell(sig)} | {'★' * stars or '0★'} | {_rarity(af)} | {zcell} |")


def full_report(snapshot_id: str) -> list[Path]:
    con = connect()
    try:
        return _full_report(con, snapshot_id)
    finally:
        con.close()  # close even on a mid-report exception (no connection leak)


def _full_report(con, snapshot_id: str) -> list[Path]:
    meta = load_manifest(snapshot_id)
    written = []

    def sortkey(r):
        # significance first, then strongest review evidence, then gene.
        return (clinsig.rank(r[6]), -_stars(r[7]), r[0] or "zzz")

    for sample in _samples_for(snapshot_id, con):
        rows = con.execute(f"""
            SELECT gene, clinvar_disease, chrom, pos, ref, alt, clinvar_sig,
                   clinvar_revstat, gnomad_af, zygosity
            FROM {TABLE}
            WHERE snapshot_id = ? AND sample_id = ?
              AND {clinsig.sql_actionable()}
        """, [snapshot_id, sample]).fetchall()

        reviewed = sorted((r for r in rows if _stars(r[7]) >= 1), key=sortkey)
        unreviewed = sorted((r for r in rows if _stars(r[7]) == 0), key=sortkey)
        ab = allele_balance.fractions(sample, [r[2:6] for r in rows])
        low = sum(allele_balance.is_low(r[9], ab.get(tuple(r[2:6]))) for r in rows)

        lines = [
            f"# FULL report — {sample}",
            "",
            f"- **Snapshot:** `{snapshot_id}`  (ClinVar {meta['clinvar_date']}, "
            f"VEP cache r{meta['vep_cache_version']}, gnomAD {meta['gnomad_version']})",
            f"- **Actionable variants:** {len(rows)} "
            f"({len(reviewed)} reviewed ≥1★, {len(unreviewed)} unreviewed 0★)",
            *([f"- **⚠️ Low allele fraction:** {low} het call(s) with under "
               f"{config.LOW_VAF_THRESHOLD:.0%} of reads carrying the variant — a real "
               f"germline het sits near 50%; review before acting on them."] if low else []),
            "",
            "## Reviewed findings (ClinVar ≥1★)",
            "",
            _HEADER, _SEP,
        ]
        lines += [_render(r, ab) for r in reviewed] or ["| _none_ | | | | | | |"]
        if unreviewed:
            lines += [
                "",
                "## Low-confidence — 0★ (submitted without review criteria)",
                "_Weak signals; often susceptibility/association entries, not "
                "monogenic disease. Interpret with caution._",
                "",
                _HEADER, _SEP,
                *[_render(r, ab) for r in unreviewed],
            ]
        if alphamissense.available():
            am_rows = []
            for gene, _d, chrom, pos, ref, alt, *_ in reviewed + unreviewed:
                am = alphamissense.lookup(chrom, pos, ref, alt)
                if am:
                    am_rows.append(f"| {gene or '?'} | {chrom}:{pos} {ref}>{alt} | "
                                   f"{alphamissense.label(am)} |")
            if am_rows:
                lines += [
                    "",
                    "## AlphaMissense — deep missense pathogenicity",
                    "_DeepMind's computational prediction for the missense variants above, "
                    "independent of ClinVar._",
                    "",
                    "| Gene | Variant | AlphaMissense |",
                    "|------|---------|---------------|",
                    *am_rows,
                ]
        if spliceai.available():
            sa_rows = []
            for gene, _d, chrom, pos, ref, alt, *_ in reviewed + unreviewed:
                sa = spliceai.lookup(chrom, pos, ref, alt)
                if sa and sa[0] >= config.SPLICEAI_DS_LOW:  # skip the no-effect majority
                    sa_rows.append(f"| {gene or sa[2] or '?'} | {chrom}:{pos} {ref}>{alt} | "
                                   f"{spliceai.label(sa)} |")
            if sa_rows:
                lines += [
                    "",
                    "## SpliceAI — deep splice-disruption prediction",
                    "_Illumina's predicted effect on splicing for the variants above "
                    "(delta score 0–1), independent of ClinVar — covers splice-region / "
                    "synonymous / intronic changes the missense predictors don't._",
                    "",
                    "| Gene | Variant | SpliceAI |",
                    "|------|---------|----------|",
                    *sa_rows,
                ]
        lines += ["", _CAVEAT, ""]
        lines += limitations.render(snapshot_id, report_kind="full", sample=sample)

        path = reportpaths.snapshot_report("full", sample, snapshot_id)
        write_report(path, lines)
        written.append(path)
        log.info("FULL report: %s (%d reviewed, %d unreviewed)",
                 path, len(reviewed), len(unreviewed))

    return written
